[0m20:19:11.584747 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d02d370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e4b7ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e4b7100>]}


============================== 20:19:11.592630 | a9418991-5dd7-458a-b726-3383d6e470df ==============================
[0m20:19:11.592630 [info ] [MainThread]: Running with dbt=1.5.0
[0m20:19:11.593700 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '../', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m20:19:11.594542 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alimir/Documents/challenge/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:19:11.595411 [debug] [MainThread]: Command `dbt run` failed at 20:19:11.595227 after 0.06 seconds
[0m20:19:11.595931 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d02d370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e4e1520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10e4e1550>]}
[0m20:19:11.596467 [debug] [MainThread]: Flushing usage events
[0m10:05:41.591503 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106abc3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f38b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f38e80>]}


============================== 10:05:41.600845 | 1002b801-b0d1-4754-aed9-d6744b5e87f6 ==============================
[0m10:05:41.600845 [info ] [MainThread]: Running with dbt=1.5.0
[0m10:05:41.601829 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '../', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m10:05:41.602644 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alimir/Documents/challenge2/data_tansformation_task/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:05:41.603507 [debug] [MainThread]: Command `dbt run` failed at 10:05:41.603313 after 0.06 seconds
[0m10:05:41.604025 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106abc3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f38e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f38f10>]}
[0m10:05:41.604549 [debug] [MainThread]: Flushing usage events
[0m10:05:49.916126 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105398520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106814fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102e01c70>]}


============================== 10:05:49.921173 | 1bc3dbab-04f7-43bf-9e8c-f28270d85e7d ==============================
[0m10:05:49.921173 [info ] [MainThread]: Running with dbt=1.5.0
[0m10:05:49.922038 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '../', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m10:05:49.922812 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/alimir/Documents/challenge2/data_tansformation_task/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:05:49.923661 [debug] [MainThread]: Command `dbt test` failed at 10:05:49.923480 after 0.03 seconds
[0m10:05:49.924267 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105398520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102e01c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106814fd0>]}
[0m10:05:49.924856 [debug] [MainThread]: Flushing usage events
